---
- name: Install apache
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - python-certbot-apache

- name: Add html files
  copy:
    src: "apache/{{ inventory_hostname }}/html/"
    dest: /var/www/html/

- name: Enable apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - ssl
    - rewrite
    - headers
    - proxy
    - proxy_http
    - deflate
    - proxy_html
    - proxy_connect
    - xml2enc

- name: Configure apache (non-ssl)
  copy:
    src: "apache/{{ inventory_hostname }}/000-default.conf"
    dest: /etc/apache2/sites-available/000-default.conf
  notify: restart apache

- name: Configure apache (ssl)
  copy:
    src: "apache/{{ inventory_hostname }}/default-ssl.conf"
    dest: /etc/apache2/sites-available/default-ssl.conf
  notify: restart apache

- file:
    src: /etc/apache2/sites-available/default-ssl.conf
    dest: /etc/apache2/sites-enabled/default-ssl.conf
    owner: root
    group: root
    state: link
  notify: restart apache
