---
- hosts: allbirds.wand.net.nz
  roles:
    - role: common
    - role: libvirt
    - role: ovs-dpdk-switch
- hosts: faucet.redcables.wand.nz
  roles:
    - role: bearwall
    - role: common
    - role: bird
    - role: dhcp
    - role: dhcpv6
    - role: freeradius
    - role: unbound
    - role: faucet
- hosts: nat64.redcables.wand.nz
  roles:
    - role: common
    - role: bird
    - role: dhcpv6
    - role: unbound
    - role: jool
    - role: routing
- hosts: monitoring.redcables.wand.nz
  roles:
    - role: bearwall
    - role: common
    - role: gauge
    - role: smokeping
    - role: prometheus
    - role: apache
- hosts: amp.redcables.wand.nz
  roles:
    - role: bearwall
    - role: common
    - role: apache
    - role: amp-server
- hosts: unifi
  roles:
    - role: common
    - role: unifi
