---
- name: Disable systemd-resolved
  systemd:
    name: systemd-resolved
    masked: yes
    state: stopped
  when: ansible_connection != 'docker'

- name: Install unbound
  apt:
    name: unbound
    state: present

- name: Configure unbound
  copy:
    src: "../../files/unbound/{{ inventory_hostname }}/"
    dest: /etc/unbound/unbound.conf.d/
  notify: restart unbound
