---
- name: Install faucet dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - python-pip
    - python-dev

- name: Create faucet group
  group:
    name: faucet
    system: yes
    state: present

- name: Create faucet user
  user:
    name: faucet
    group: faucet
    createhome: no
    system: yes
    state: present

- name: Install faucet
  pip:
    name: ryu-faucet

- name: Add faucet defaults file
  copy:
    src: default
    dest: /etc/default/faucet

- name: Add faucet-at defaults file
  copy:
    src: default-at
    dest: /etc/default/faucet-at

- name: Configure ryu
  copy:
    src: ryu.conf
    dest: /etc/ryu/

- name: Create faucet log directory
  file:
    path: /var/log/ryu/faucet/
    owner: faucet
    group: faucet
    recurse: yes
    state: directory

- name: Add faucet systemd unit
  copy:
    src: faucet.service
    dest: /etc/systemd/system/

- name: Add faucet-at systemd unit
  copy:
    src: faucet-at.service
    dest: /etc/systemd/system/

- name: Enable faucet systemd unit
  systemd:
    name: faucet
    daemon_reload: yes
    masked: no
    state: started

- name: Enable faucet-at systemd unit
  systemd:
    name: faucet-at
    daemon_reload: yes
    masked: no
    state: started

- name: Add acls-common.yaml
  copy:
    src: acls-common.yaml
    dest: /etc/ryu/faucet/
  notify: reload faucet

- name: Add vlans-common.yaml
  copy:
    src: vlans-common.yaml
    dest: /etc/ryu/faucet/
  notify: reload faucet

- name: Add faucet.yaml
  copy:
    src: faucet.yaml
    dest: /etc/ryu/faucet/
  notify: reload faucet


- name: Add faucet-at.yaml
  copy:
    src: faucet-at.yaml
    dest: /etc/ryu/faucet/
  notify: reload faucet-at
