---
- name: Install faucet dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - python3-pbr
    - git

- name: Create faucet group
  group:
    name: faucet
    system: yes
    state: present

- name: Create faucet user
  user:
    name: faucet
    group: faucet
    createhome: no
    system: yes
    state: present

- name: Remove faucet from python2
  pip:
    name: faucet
    executable: pip
    state: absent

- name: Remove ryu from python2
  pip:
    name: ryu
    executable: pip
    state: absent

- name: Install faucet
  pip:
    name: faucet
    executable: pip3
    version: "{{ faucet_version }}"
    state: present
  notify:
    - restart faucet
    - restart faucet-l2

- name: Add faucet defaults file
  copy:
    src: default
    dest: /etc/default/faucet

- name: Add faucet-l2 defaults file
  copy:
    src: default-l2
    dest: /etc/default/faucet-l2

- name: Create faucet config directory
  file:
    path: /etc/ryu/faucet/
    owner: root
    group: root
    recurse: yes
    state: directory

- name: Configure ryu
  copy:
    src: ryu.conf
    dest: /etc/ryu/

- name: Create faucet log directory
  file:
    path: /var/log/ryu/faucet/
    owner: faucet
    group: faucet
    recurse: yes
    state: directory

- name: Add faucet systemd unit
  copy:
    src: faucet.service
    dest: /etc/systemd/system/

- name: Add faucet-l2 systemd unit
  copy:
    src: faucet-l2.service
    dest: /etc/systemd/system/

- name: Enable faucet systemd unit
  systemd:
    name: faucet
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

- name: Enable faucet-l2 systemd unit
  systemd:
    name: faucet-l2
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

- name: Add common faucet configuration
  copy:
    src: faucet/common/
    dest: /etc/ryu/faucet/common/
  notify:
    - reload faucet
    - reload faucet-l2

- name: Add faucet configuration
  copy:
    src: faucet/faucet.yaml
    dest: /etc/ryu/faucet/
  notify:
    - reload faucet

- name: Add faucet-l2 configuration
  copy:
    src: faucet/faucet-l2.yaml
    dest: /etc/ryu/faucet/
  notify:
    - reload faucet-l2

- name: Check faucet config
  shell: check_faucet_config /etc/ryu/faucet/faucet.yaml

- name: Check faucet-l2 config
  shell: check_faucet_config /etc/ryu/faucet/faucet-l2.yaml
