---
- name: Install faucet dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - python-pip
    - python-dev
    - python-pbr
    - git

- name: Create faucet group
  group:
    name: faucet
    system: yes
    state: present

- name: Create faucet user
  user:
    name: faucet
    group: faucet
    createhome: no
    system: yes
    state: present

- name: Install ryu
  pip:
    name: git+https://github.com/osrg/ryu#egg=ryu
    editable: false
    state: present

- name: Install faucet
  pip:
    name: git+https://github.com/reannz/faucet#egg=faucet
    editable: false
    state: latest
  notify:
    - restart faucet
    - restart faucet-at

- name: Add faucet defaults file
  copy:
    src: default
    dest: /etc/default/faucet

- name: Add faucet-at defaults file
  copy:
    src: default-at
    dest: /etc/default/faucet-at

- name: Create faucet config directory
  file:
    path: /etc/ryu/faucet/
    owner: root
    group: root
    recurse: yes
    state: directory

- name: Configure ryu
  copy:
    src: ryu.conf
    dest: /etc/ryu/

- name: Create faucet log directory
  file:
    path: /var/log/ryu/faucet/
    owner: faucet
    group: faucet
    recurse: yes
    state: directory

- name: Add faucet systemd unit
  copy:
    src: faucet.service
    dest: /etc/systemd/system/

- name: Add faucet-at systemd unit
  copy:
    src: faucet-at.service
    dest: /etc/systemd/system/

- name: Enable faucet systemd unit
  systemd:
    name: faucet
    daemon_reload: yes
    masked: no
    state: started

- name: Enable faucet-at systemd unit
  systemd:
    name: faucet-at
    daemon_reload: yes
    masked: no
    state: started

- name: Add faucet configuration
  copy:
    src: faucet/
    dest: /etc/ryu/faucet/
  notify:
    - reload faucet
    - reload faucet-at

- name: Check faucet config
  shell: check_faucet_config /etc/ryu/faucet/faucet.yaml

- name: Check faucet-at config
  shell: check_faucet_config /etc/ryu/faucet/faucet-at.yaml
