---
version: 2

include:
    - acls-common.yaml
    - vlans-common.yaml

dps:
    at-x930-1:
        dp_id: 0xeccd6df7d4aa
        description: "at-x930-1"
        hardware: "Allied-Telesis"
        ignore_learn_ins: 50
        drop_spoofed_faucet_mac: False
        interfaces:
            1:
                native_vlan: control
                tagged_vlans: [nznog-v6-l2,nznog-v4v6-l2]
                name: "port1.0.1"
                acl_in: protect_from_access
            2:
                native_vlan: nznog-v4v6-l2
                name: "port1.0.2"
                acl_in: protect_from_access
            3:
                native_vlan: control
                tagged_vlans: [nznog-v6-l2,nznog-v4v6-l2]
                name: "port1.0.3"
                acl_in: protect_from_access
            4:
                native_vlan: control
                tagged_vlans: [nznog-v6-l2,nznog-v4v6-l2]
                name: "port1.0.4"
                acl_in: protect_from_access
            5:
                native_vlan: nznog-v6-l2
                name: "port1.0.5"
                acl_in: protect_from_access
            6:
                native_vlan: nznog-v6-l2
                name: "port1.0.6"
                acl_in: protect_from_access
            7:
                native_vlan: nznog-v4v6-l2
                name: "port1.0.7"
                acl_in: protect_from_access
            8:
                native_vlan: nznog-v4v6-l2
                name: "port1.0.8"
                acl_in: protect_from_access
            20:
                tagged_vlans: [control,nznog-v4v6-l2]
                name: "port1.0.20"
                description: "link022 wifi ap"
                acl_in: protect_from_access
            23:
                tagged_vlans: [nznog-v6-l2]
                name: "port1.0.23"
                description: "at-x930-1 nznog6 trunk"
            24:
                tagged_vlans: [nznog-v4v6-l2,control]
                name: "port1.0.24"
                description: "at-x930-1 nznog trunk"
            25:
                tagged_vlans: [nznog-v4v6-l2]
                name: "port1.0.25"
                description: "internet"
                acl_in: protect_from_edge
    at-x930-2:
        dp_id: 0xeccd6def54ff
        description: "at-x930-2"
        hardware: "Allied-Telesis"
        ignore_learn_ins: 50
        drop_spoofed_faucet_mac: False
        interfaces:
            1:
                native_vlan: control
                tagged_vlans: [nznog-v6-l2,nznog-v4v6-l2]
                name: "port1.0.1"
                acl_in: protect_from_access
            2:
                native_vlan: control
                tagged_vlans: [nznog-v6-l2,nznog-v4v6-l2]
                name: "port1.0.2"
                acl_in: protect_from_access
            3:
                native_vlan: control
                tagged_vlans: [nznog-v6-l2,nznog-v4v6-l2]
                name: "port1.0.3"
                acl_in: protect_from_access
            4:
                native_vlan: control
                tagged_vlans: [nznog-v6-l2,nznog-v4v6-l2]
                name: "port1.0.4"
                acl_in: protect_from_access
            5:
                native_vlan: nznog-v6-l2
                name: "port1.0.5"
                acl_in: protect_from_access
            6:
                native_vlan: nznog-v6-l2
                name: "port1.0.6"
                acl_in: protect_from_access
            7:
                native_vlan: nznog-v4v6-l2
                name: "port1.0.7"
                acl_in: protect_from_access
            8:
                native_vlan: nznog-v4v6-l2
                name: "port1.0.8"
                acl_in: protect_from_access
            20:
                tagged_vlans: [control,nznog-v4v6-l2]
                name: "port1.0.20"
                description: "link022 wifi ap"
                acl_in: protect_from_access
            23:
                tagged_vlans: [nznog-v6-l2]
                name: "port1.0.23"
                description: "at-x930-2 nznog6 trunk"
            24:
                tagged_vlans: [nznog-v4v6-l2,control]
                name: "port1.0.24"
                description: "at-x930-2 nznog trunk"
            25:
                native_vlan: nznog-v4v6-l2
                name: "port1.0.26"
                description: "to redcables-core-sw 1/xg2"
