---
version: 2

include:
    - acls-common.yaml
    - vlans-common.yaml

vlans:
    nznog-v4v6-l3:
        name: "nznog-v4v6-l3"
        description: "nznog ipv4/ipv6 routed vlan"
        vid: 20
        controller_ips: ['202.74.195.254/22', '14.1.63.155/29', '2401:7000:69:4000::ffff/64', '2401:7000:0:ab::f/124', 'fe80::20d:88ff:fe00:aa/64']
        bgp_port: 9179
        bgp_as: 9727
        bgp_routerid: '127.0.0.2'
        bgp_neighbor_addresses: ['127.0.0.1', '::1']
        bgp_neighbor_as: 9727
        routes:
            - route:
                ip_dst: '2401:7000:69::/64'
                ip_gw: '2401:7000:0:ab::3'
            - route:
                ip_dst: '202.74.195.0/25'
                ip_gw: '202.74.195.252'

dps:
    ovs-nznog:
        dp_id: 0xa0369f4b02e8
        hardware: "Open vSwitch"
        ignore_learn_ins: 10
        arp_neighbor_timeout: 600
        drop_spoofed_faucet_mac: False
        interfaces:
            1:
                native_vlan: nznog-v4v6-l3
                name: 'vhost-nat64-nznog'
                description: "nat64 vm"
                acl_in: protect_from_access
            2:
                native_vlan: nznog-v4v6-l3
                name: 'vhost-faucet-nznog'
                description: "faucet vm"
                acl_in: protect_from_core
            3:
                native_vlan: nznog-v4v6-l3
                name: 'dpdk2'
                description: "test port"
                acl_in: protect_from_access
            4:
                tagged_vlans: [nznog-v4v6-l3,control]
                name: 'dpdk4'
                description: "at-x930-1 nznog trunk"
            5:
                tagged_vlans: [nznog-v4v6-l3,control]
                name: 'dpdk5'
                description: "at-x930-2 nznog trunk"
            6:
                native_vlan: nznog-v4v6-l3
                name: 'vhost-host-nznog'
                description: "host-nznog vm"
                acl_in: protect_from_access
            7:
                tagged_vlans: [nznog-v4v6-l3]
                name: 'internet'
                description: "internet uplink"
                acl_in: protect_from_edge
            8:
                native_vlan: nznog-v4v6-l3
                name: 'unifi'
                description: "unifi controller vm"
                acl_in: protect_from_access
            9:
                native_vlan: nznog-v4v6-l3
                name: 'smokeping'
                description: "smokeping controller vm"
                acl_in: protect_from_access
            10:
                native_vlan: nznog-v4v6-l3
                name: 'awdy'
                description: "awdy vm"
                acl_in: protect_from_access
            20:
                native_vlan: control
                name: "vhost-faucet-control"
                description: "faucet vm openflow channel"
                acl_in: protect_from_control
            21:
                native_vlan: control
                name: "dpdk0"
                description: "at-x930-1 openflow channel"
                acl_in: protect_from_control
            22:
                native_vlan: control
                name: "dpdk1"
                description: "at-x930-2 openflow channel"
                acl_in: protect_from_control
            23:
                native_vlan: control
                name: "unifi"
                description: "unifi controller vm"
                acl_in: protect_from_control
    ovs-nznog6:
        dp_id: 0xa0369f5d0a22
        hardware: "Open vSwitch"
        ignore_learn_ins: 10
        arp_neighbor_timeout: 600
        drop_spoofed_faucet_mac: False
        interfaces:
            1:
                native_vlan: nznog-v6-l2
                name: 'vhost-nat64-nznog6'
                description: "nat64 vm"
                acl_in: protect_from_core
            2:
                native_vlan: nznog-v6-l2
                name: 'vhost-host-nznog6'
                description: "host-nznog6 vm"
                acl_in: protect_from_access
            6:
                tagged_vlans: [nznog-v6-l2]
                name: 'dpdk6'
                description: "at-x930-1 nznog6 trunk"
            7:
                tagged_vlans: [nznog-v6-l2]
                name: 'dpdk7'
                description: "at-x930-2 nznog6 trunk"
