---
version: 2

vlans:
    nznog-v6-l2:
        name: "nznog-v6-l2"
        description: "nznog ipv6-only vlan"
        vid: 10
    nznog-v4v6-l2:
        name: "nznog-v4v6-l2"
        description: "nznog ipv4/ipv6 vlan"
        vid: 20
    control:
        name: "control"
        description: "openflow control vlan"
        vid: 99
