---

- name: Uninstall prometheus-pushgateway package
  apt:
    name: prometheus-pushgateway
    purge: yes
    state: absent

- name: Create prometheus group
  group:
    name: prometheus
    system: yes
    state: present

- name: Create prometheus user
  user:
    name: prometheus
    group: prometheus
    createhome: no
    system: yes
    state: present

- name: Create prometheus-pushgateway install directory
  file:
    path: /opt/prometheus/pushgateway
    owner: prometheus
    group: prometheus
    recurse: yes
    state: directory

- name: Create prometheus lib directory
  file:
    path: /var/lib/prometheus/
    owner: prometheus
    group: prometheus
    recurse: yes
    state: directory

- name: Configure prometheus-pushgateway
  copy:
    src: default
    dest: /etc/default/prometheus-pushgateway
  notify: restart prometheus-pushgateway

- name: Install prometheus-pushgateway
  unarchive:
    src: "https://github.com/prometheus/pushgateway/releases/download/v{{ prometheus_pushgateway_version }}/pushgateway-{{ prometheus_pushgateway_version }}.linux-amd64.tar.gz"
    dest: "/opt/prometheus/pushgateway"
    extra_opts: "--strip-components=1"
    owner: prometheus
    group: prometheus
    remote_src: yes

- name: Add prometheus-pushgateway systemd unit
  copy:
    src: prometheus-pushgateway.service
    dest: /etc/systemd/system/

- name: Enable prometheus-pushgateway systemd unit
  systemd:
    name: prometheus-pushgateway
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started
