---
- name: Install kvm
  apt:
    name: qemu-kvm
    state: installed

- name: Install libvirt
  apt:
    name: libvirt-bin
    state: installed
  register: libvirt_install_result

- name: Install libvirt python bindings
  apt:
    name: python-libvirt
    state: installed

- name: Define faucet VM
  virt:
    name: faucet
    command: define
    xml: "{{ lookup('template', 'faucet.xml.j2') }}"
    uri: 'qemu:///system'
  when: libvirt_install_result.changed

- name: Define nat64 VM
  virt:
    name: nat64
    command: define
    xml: "{{ lookup('template', 'nat64.xml.j2') }}"
    uri: 'qemu:///system'
  when: libvirt_install_result.changed
