---
- name: Install kvm
  apt:
    name: qemu-kvm
    state: installed

- name: Install libvirt
  apt:
    name: libvirt-bin
    state: installed
  register: libvirt_install_result

- name: Install libvirt python bindings
  apt:
    name: python-libvirt
    state: installed

- name: Install libvirt OVS ifup script
  copy:
    src: qemu-ifup-nznog
    dest: /etc/qemu-ifup-nznog
    mode: a+x

- name: Configure apparmor
  copy:
    src: usr.sbin.libvirtd
    dest: /etc/apparmor.d/
  notify: restart apparmor

- name: Define faucet VM
  virt:
    name: faucet
    command: define
    xml: "{{ lookup('template', 'faucet.xml.j2') }}"
    uri: 'qemu:///system'
  when: libvirt_install_result.changed

- name: Define nat64 VM
  virt:
    name: nat64
    command: define
    xml: "{{ lookup('template', 'nat64.xml.j2') }}"
    uri: 'qemu:///system'
  when: libvirt_install_result.changed
