---
- name: Install smokeping
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - smokeping

- name: Configure smokeping
  copy:
    src: smokeping/
    dest: /etc/smokeping/config.d/
  notify: restart smokeping

- name: Remove default apache smokeping config
  file:
    path: /etc/apache2/conf-enabled/smokeping.conf
    state: absent
  notify: restart apache

- name: Enable mod_rewrite apache module
  apache2_module:
    name: rewrite
    state: present

- name: Configure apache
  copy:
    src: 000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
  notify: restart apache
