---
- name: Install gauge dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - python-pip
    - python-dev

- name: Create faucet group
  group:
    name: faucet
    system: yes
    state: present

- name: Create faucet user
  user:
    name: faucet
    group: faucet
    createhome: no
    system: yes
    state: present

- name: Install gauge
  pip:
    name: faucet
    state: present
  notify: restart gauge

- name: Add gauge defaults file
  copy:
    src: default
    dest: /etc/default/gauge

- name: Create faucet config directory
  file:
    path: /etc/ryu/faucet/
    owner: root
    group: root
    recurse: yes
    state: directory

- name: Configure ryu
  copy:
    src: ryu.conf
    dest: /etc/ryu/

- name: Create gauge log directory
  file:
    path: /var/log/ryu/faucet/
    owner: faucet
    group: faucet
    recurse: yes
    state: directory

- name: Add gauge systemd unit
  copy:
    src: gauge.service
    dest: /etc/systemd/system/

- name: Enable gauge systemd unit
  systemd:
    name: gauge
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

- name: Configure gauge
  template:
    src: gauge.yaml.j2
    dest: /etc/ryu/faucet/gauge.yaml
  notify: restart gauge

- name: Add faucet configuration
  copy:
    src: faucet/
    dest: /etc/ryu/faucet/
  notify: restart gauge
