---
- name: Import packagecloud GPG signing key
  apt_key:
    url: https://packagecloud.io/gpg.key
    state: present

- name: Add grafana repository
  apt_repository:
    repo: "deb https://packagecloud.io/grafana/stable/debian/ jessie main"
    state: present

- name: Install grafana
  apt:
    name: grafana
    state: present

- name: Grant CAP_NET_BIND_SERVICE to grafana
  capabilities:
    path: /usr/sbin/grafana-server
    capability: cap_net_bind_service+ep
    state: present

- name: Enable grafana systemd unit
  systemd:
    name: grafana-server
    daemon_reload: yes
    masked: no
    state: started

- name: Configure grafana
  copy:
    src: grafana.ini
    dest: /etc/grafana/
  notify: restart grafana
