---

- name: Install isc-dhcp-server
  apt:
    name: isc-dhcp-server
    state: present

- name: Install dhcpd-pools
  apt:
    name: dhcpd-pools
    state: present

- name: Configure isc-dhcp-server
  copy:
    src: "dhcp/{{ inventory_hostname }}/dhcpd.conf"
    dest: /etc/dhcp/
  notify: restart isc-dhcp-server

- name: Configure isc-dhcp-server default file
  copy:
    src: "dhcp/{{ inventory_hostname }}/default"
    dest: /etc/default/isc-dhcp-server
  notify: restart isc-dhcp-server
