---

- name: Install isc-dhcp-server
  apt:
    name: isc-dhcp-server
    state: present

- name: Create dhcpd group
  group:
    name: dhcpd
    system: yes
    state: present

- name: Create dhcpd user
  user:
    name: dhcpd
    group: dhcpd
    createhome: no
    system: yes
    state: present

- name: Add isc-dhcp-server systemd unit
  copy:
    src: isc-dhcp-server.service
    dest: /etc/systemd/system/

- name: Enable isc-dhcp-server systemd unit
  systemd:
    name: isc-dhcp-server
    daemon_reload: yes
    masked: no
    state: started

- name: Configure isc-dhcp-server
  copy:
    src: "{{ inventory_hostname }}/dhcpd.conf"
    dest: /etc/dhcp/
  notify: restart isc-dhcp-server
