---

- name: Install isc-dhcp-server
  apt:
    name: isc-dhcp-server
    state: present

- name: Configure isc-dhcp-server
  copy:
    src: "../../files/dhcp/{{ inventory_hostname }}/dhcpd.conf"
    dest: /etc/dhcp/
  notify: restart isc-dhcp-server
  when: ansible_connection != 'docker'

- name: Configure isc-dhcp-server default file
  copy:
    src: "../../files/dhcp/{{ inventory_hostname }}/default"
    dest: /etc/default/isc-dhcp-server
  notify: restart isc-dhcp-server
  when: ansible_connection != 'docker'
