---
- name: Import unifi GPG signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C0A52C50
    state: present

- name: Add unifi repository
  apt_repository:
    repo: "deb http://www.ubnt.com/downloads/unifi/debian unifi5 ubiquiti"
    state: present

- name: Install unifi
  apt:
    name: unifi
    state: present
