---
- name: restart networking
  service:
    name: networking.service
    state: restarted

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart prometheus-node-exporter
  service:
    name: prometheus-node-exporter
    state: restarted
