---
- name: Set net.ipv4.conf.all.forwarding
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: 1
    sysctl_file: /etc/sysctl.d/20-routing.conf

- name: Set net.ipv6.conf.all.forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    sysctl_file: /etc/sysctl.d/20-routing.conf
