---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')

- name: Set hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1.+$"
    line: "127.0.1.1    {{ ansible_fqdn }} {{ ansible_hostname }}"
  when: ansible_connection != 'docker'

- name: Configure network interfaces
  copy:
    src: "interfaces/{{ inventory_hostname }}/interfaces"
    dest: /etc/network/interfaces
  notify: restart networking
  when: ansible_connection != 'docker'

- name: Disable ssh password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication"
    line: "PasswordAuthentication no"
    backrefs: yes
    state: present
  notify: restart ssh
  when: ansible_connection != 'docker'

- name: Install useful packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - apt-transport-https
    - dnsutils
    - ethtool
    - htop
    - tcpdump
    - vim
    - screen
    - prometheus-node-exporter

- name: Enable prometheus-node-exporter systemd unit
  systemd:
    name: prometheus-node-exporter
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started
  when: ansible_connection != 'docker'

- name: Configure prometheus-node-exporter
  template:
    src: prometheus-node-exporter.j2
    dest: /etc/default/prometheus-node-exporter
  notify: restart prometheus-node-exporter
