---

- name: Install isc-dhcp-server
  apt:
    name: isc-dhcp-server
    state: present

- name: Configure isc-dhcp-server6
  copy:
    src: "dhcp/{{ inventory_hostname }}/dhcpd6.conf"
    dest: /etc/dhcp/
  notify: restart isc-dhcp-server

- name: Configure isc-dhcp-server default file
  copy:
    src: "dhcp/{{ inventory_hostname }}/default"
    dest: /etc/default/isc-dhcp-server
  notify: restart isc-dhcp-server

- name: Enable isc-dhcp-server systemd unit
  service:
    name: isc-dhcp-server
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started
