---

- name: Install isc-dhcp-server
  apt:
    name: isc-dhcp-server
    state: present

- name: Enable isc-dhcp-server systemd unit
  service:
    name: isc-dhcp-server
    daemon_reload: yes
    masked: no
    state: started

- name: Configure isc-dhcp-server6
  copy:
    src: "dhcpv6/{{ inventory_hostname }}/dhcpd6.conf"
    dest: /etc/dhcp/
  notify: restart isc-dhcp-server
